### ISSUE TITLE
Loading flatted files

### ISSUE THREAD

**Issue by oabsil** [vortex-exoplanet/NIRC2_Preprocessing#1]
Hi @owertz 

Wouldn't it be nice to have an option to load flatted sci and sky files instead of recomputing them, in case they are already stored in the "processed" folder? That would save some time, especially when there are a lot of files.

Cheers,
Oli.

**Comment by ghost** [comment]
Hi @oabsil 

I've taken into account your suggestion. I've created an new function **load_images()** simply based on listing() and create_cube_from_frames(). With this new function, the load of a set of images can be done in one line into the NIRC2_Preprocessing_ streamlined notebook.

Cheers,
Oli
