### ISSUE TITLE
Vortex center coordinates issues

### ISSUE THREAD

**Issue by ehuby** [vortex-exoplanet/NIRC2_Preprocessing#18]
Hi @henry-ngo  and @oabsil,

Lately, I've been investigating the cube_registration and vortex_center_from_dust_signature functions quite in detail. I'd like to share here 2 comments / suggestions that I have that could improve the functions.

1- There currently is an issue if the rough estimates of the dust/vortex center coordinates are given as decimals (i.e. not rounded to integer values). For instance, if you specify vortex_center = (519.5, 730.) within the input vortex_options structure, the returned x coordinates will be offset by 0.5 pixel.
I propose to fix this by adding these lines after line 1172:
cx = int(np.round(cx))
cy = int(np.round(cy))

2- I noticed that the coordinates that are returned by vortex_center_from_dust_signature are, by default, given in the reference frame of the DS9 display (starting at pixel 1 instead of 0 in python), i.e. there's a shift of 1 pixel with respect to the actual coordinates that are used in python. It is in itself not a problem, since this is taken into account internally in the cube_registration function, but it can be confusing.
There's actually a keyword, ds9_indexing appearing in the sub-functions, which is set to True by default, thus inducing the 1 pixel shift, but it could be set to False to avoid it. However, this keyword is not available as input of vortex_center_from_dust_signature.
I would actually suggest that we remove this option completely and make all coordinates start from 0, to avoid any confusion.

Cheers,
Elsa.

**Comment by henry-ngo** [comment]
Hi Elsa, thanks for these suggestions! I have implemented both of them in the latest commit (#19).
