### ISSUE TITLE
Cube registration crash + save file name

### ISSUE THREAD

**Issue by oabsil** [vortex-exoplanet/NIRC2_Preprocessing#2]
Hi @owertz 

I noted that the cube registration was crashing when using verbose=False, because start_time was not defined. I have implemented a fix, which also relies on the addition of a "verbose" keyword to timeInit in VIP. We can review that together later today and commit the change if you're ok.

By the way, I'm currently working on a RDI-oriented version of the notebook, where the sky is removed from the frames before applying RDI-PCA. For that, I need to register and crop the sky(s) in the same way as the sci frames. The problem I'm encountering is that the saved output fits file has the same name for the sci and sky registered frames. I've added a "filename" keyword in cube_registration to tune the filename (it replaces the string 'cube' in the output file name by whatever string you chose).

Cheers,
Oli

**Comment by ghost** [comment]
Hi @oabsil 

Concerning the bug:
Thanks for having reported this bug. As you've already noticed, the _start_time_ variable was defined in the "if verbose" condition, which led to the error. Thanks for your fix.

Concerning the RDI-oriented:
This update is now committed.

Cheers,
Oli
