### ISSUE TITLE
Concatenation of path names

### ISSUE THREAD

**Issue by mb2448** [vortex-exoplanet/NIRC2_Preprocessing#5]
**_Problem:**_
There are often errors in the output paths of the NIRC2_Preprocessing module, where I specify an output path for a function and instead get the output path concatenated with the intended subdirectory.  

For example, if I specify the output directory 

```
/Volumes/TRANS_SSD/keckdata/ab_aur/abaur_reduction
```

and a list of files in the directory `/Volumes/TRANS_SSD/keckdata/ab_aur/targs/`, the output from `applyFlat` will live in a directory created by `applyFlat` called `abaur_reductiontargs_flatted` instead of `abaur_reduction/targs_flatted`

**_Cause:**_
A lot of this is due to the paths being manipulated at the _string_ level rather than the Python-recommended _path_ level.  The symptom of this approach is in the lines 578-582

``` python
    if save:
        # Determine the last / in the filepath to deduce the file path and the 
        # last . to deduce the file name.
        index_0 = [k for k,letter in enumerate(fileList[0]) if letter == '/'] 
        index_1 = [j for j,letter in enumerate(fileList[0]) if letter =='.']    

```

Consider the following line, line 592 in `NIRC2_Preprocessing.py`

``` python
subrep_in_path_output = path_output+fileList[0][index_0[-2]+1:index_0[-1]]+'_flatted/'
```

The code tries to read the parent directory of the file list and add '_flatted' to it.  If the **path_output** directory happens to not have a **/** at the end, the code will concatenate the paths, since the **+** operator is used to join the paths instead of **os.path.join**.  Also, in terms of readability it is difficult to understand what is going on with the string-level indexing.

Similarly, the line 

``` python
filename = filepath[index_0[-1]+1:index_1[-1]]
```

uses the same string indexing tricks to extract `n0376` from `/Volumes/TRANS_SSD/keckdata/ab_aur/targs/n0376.fits`

**_Solution:**_
To solve the previous issue, the safe way is to use 

``` python
os.path.basename(filepath).split('.')[0]
```

To solve the first issue, a safe way to implement this without having path-merging occur is

``` python
    os.path.join(path_output, 
                       os.path.basename(
                             os.path.dirname(fileList[0])) +'_flatted')
```

In this way, the **+** operator is used to modify the _name_ of the directory, and the **os.path.join** is used to _join_ the directories.  In general, the **os.path** module should be used over the string indexing tricks.  No issues with missing **/**s or pathological filenames (such as periods in the filenames) will ever occur because the **os.path** module explicitly checks and corrects for these.

**Comment by ghost** [comment]
Hi,

Thanks for the suggestions. If the output path doesn't lack a final '/', the output subdirectory should be ok. Anyway, I agree with the fact that the proposed solution leads to a more robust way to manage paths by automatically taking care of a possible missing '/'. I have updated the code here and there accordingly.

Olivier
