### ISSUE TITLE
Best practices for changes to NIRC2_Preprocessing.py

### ISSUE THREAD

**Issue by henry-ngo** [vortex-exoplanet/NIRC2_Preprocessing#6]
Hello,

I thought I should make this a separate issue/question. As I wrote in https://github.com/vortex-exoplanet/NIRC2_Preprocessing/issues/4 earlier, one of the mistakes I made was that I had an old copy of NIRC2_Preprocessing.py in the same directory as my code so that even when I pull the latest version from github (and when I make edits to that version), my code was still importing the old NIRC2_Preprocessing.py file in my code's directory instead of the updated file in the repository directory.

I fixed it by copying the file from the repository directory into the directory where my reduction code lives.

I notice that VIP has an setup.py file that I installed with the "develop" flag so that I can import it as a package and not worry about this. Since I am new to github and its structure, I wanted to ask two questions:
1. What's the recommended/usual way to handle these cases?
   a. Continue to manually copy NIRC2_Preprocessing.py each time I pull a new version?
   b. Make a soft link from my reduction code's directory to the repository?
   c. Add the local NIRC2_Preprocessing repository to my python path?
   d. Something else?
2. Will NIRC2_Preprocessing eventually have a setup.py file created so that it could be imported the same way as VIP?

**Comment by ghost** [comment]
Hi Henry,

Thanks for your message. I will start by answering the second question: yes, I plan to make it a Python module with a setup.py file. It's on my to-do list :-) Meanwhile, I would suggest either b or c.

Olivier

**Comment by oabsil** [comment]
Sorry I answered in the wrong thread. Here is it again, for the record:

Dear Henry,

I'm generally using the following trick to make sure that I'm using the 
proper version of NIRC2_Preprocessing.py. You may find it useful:

---

# Add NIRC2_Preprocessing in your system path if needed

import sys
sys.path.insert(0, '/Users/oabsil/Python/NIRC2_Preprocessing/')

# Import all relevant packages

from NIRC2_Preprocessing import *

---

This also allows you to put your notebook in any directory you like (not 
necessarily in the NIRC2_Preprocessing folder), and to keep only one 
copy of NIRC2_Preprocessing.py on your machine (the one that is linked 
to sourcetree).

Cheers,
Olivier.

Le 16/12/15 00:47, Henry Ngo a écrit :

> Hello,
> 
> I thought I should make this a separate issue/question As I wrote in 
> https://githubcom/vortex-exoplanet/NIRC2_Preprocessing/issues/4 
> earlier, one of the mistakes I made was that I had an old copy of 
> NIRC2_Preprocessingpy in the same directory as my code so that even 
> when I pull the latest version from github (and when I make edits to 
> that version), my code was still importing the old 
> NIRC2_Preprocessingpy file in my code's directory instead of the 
> updated file in the repository directory
> 
> I fixed it by copying the file from the repository directory into the 
> directory where my reduction code lives
> 
> I notice that VIP has an setuppy file that I installed with the 
> "develop" flag so that I can import it as a package and not worry 
> about this Since I am new to github and its structure, I wanted to ask 
> two questions:
> 
> 1 What's the recommended/usual way to handle these cases?
> a Continue to manually copy NIRC2_Preprocessingpy each time I pull a 
> new version?
> b Make a soft link from my reduction code's directory to the repository?
> c Add the local NIRC2_Preprocessing repository to my python path?
> d Something else?
> 
> 2 Will NIRC2_Preprocessing eventually have a setuppy file created so 
> that it could be imported the same way as VIP?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/vortex-exoplanet/NIRC2_Preprocessing/issues/6.

## 

---

Dr. Olivier ABSIL
F.R.S.-FNRS Research Associate
Dept. of Astrophysics, Geophysics and Oceanography
Université de Liège (ULg), bât. B5c
17 allée du Six Août       Tel: +32-(0)4-366.97.24
B-4000 Sart-Tilman         Fax: +32-(0)4-366.97.46

## Email: absil (at) astro.ulg.ac.be

**Comment by henry-ngo** [comment]
Thanks, I'll do this! :)
