### ISSUE TITLE
Using NIRC2_Preprocessing.py and updated vip pipeline

### ISSUE THREAD

**Issue by tmesh** [vortex-exoplanet/NIRC2_Preprocessing#7]
First of all, thanks for the fabulous work you've done with VIP and the NIRC2 preprocessing code, this is really great. I have an issue with NIRC2_preprocessing.py, specifically it imports:

from vip.fits import display_array_ds9, write_fits

Which I believe is an old function which no longer exists in vip. Is there an updated version of NIRC2_preprocessing.py? There may be other issues with inconsistencies, but this is the first one that came up.

Thanks!
Tiffany

**Comment by ghost** [comment]
Hi Tiffany,

Many thanks for your kind words. 

I've updated the NIRC2_preprocessing.py code in such a way it's now compatible with the vip version 0.4.3. It should be stable but don't hesitate to open a new issue if you spot other incompatibilities. 

Cheers,
Olivier

**Comment by tmesh** [comment]
Hi Olivier,

Thanks! I have another issue now, my apologies if this is explained somewhere already. How do I handle the preprocessing of the off-axis, unsaturated, "PSF" image of the star? For each target I have a sky and off-axis PSF image but I don't think I have the matching flat. Is that something I can find in the archive or is this handled by the NIRC2_Preprocessing code somehow?

Right now it gets an error when it tries to divide the flat because it's a different image size.

Thanks,
Tiffany

**Comment by oabsil** [comment]
Hi Tiffany,

I don't know if Olivier has had the time to answer before leaving (he's 
gonna be skiing for the next 7 days). So here are some elements of answer:
- There is no specific flat for the PSF. In principle, you can create 
  the flats yourself by cropping the full-frame flats to the appropriate size.
- To my knowledge, there isn't any specific function in 
  NIRC2_preprocessing for that purpose, although some functions can 
  probably be used to process the off-axis PSF.
- Olivier has probably already produced a PSF template for his work on 
  the HR8799 planets, so maybe he could send you a clean PSF right away. 
  If he does not answer promplty, you can also contact Maddalena 
  (mreggiani@ulg.ac.be), as I know she's been trying to measure the 
  astrometry of some possible companions in her NIRC2+AGPM data.

Cheers,
Olivier.

Le 19/02/16 02:01, Tiffany Meshkat a écrit :

> Hi Olivier,
> 
> Thanks! I have another issue now, my apologies if this is explained 
> somewhere already. How do I handle the preprocessing of the off-axis, 
> unsaturated, "PSF" image of the star? For each target I have a sky and 
> off-axis PSF image but I don't think I have the matching flat. Is that 
> something I can find in the archive or is this handled by the 
> NIRC2_Preprocessing code somehow?
> 
> Right now it gets an error when it tries to divide the flat because 
> it's a different image size.
> 
> Thanks,
> Tiffany
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/vortex-exoplanet/NIRC2_Preprocessing/issues/7#issuecomment-185999479.

## 

---

Dr. Olivier ABSIL
F.R.S.-FNRS Research Associate
Dept. of Astrophysics, Geophysics and Oceanography
Université de Liège (ULg), bât. B5c
17 allée du Six Août       Tel: +32-(0)4-366.97.24
B-4000 Sart-Tilman         Fax: +32-(0)4-366.97.46

## Email: absil (at) astro.ulg.ac.be
