### ISSUE TITLE
Request: bad pixel mapping from NIRC2 flats

### ISSUE THREAD

**Issue by henry-ngo** [vortex-exoplanet/NIRC2_Preprocessing#8]
Hello!

Recently, when Dimitri and I tried to build a super-cube with vip for RDI processing, we notice that we have a lot of trouble finding frames with enough correlation. After inspecting the frames, we see that there are image artifacts due to bad pixels that might be making it hard for VIP to find correlations.

I inspected the "master" function in NIRC2_Preprocessing (the wrapper is "masterFlat") and notice that there is currently very little filtering options for creating the master flat. 

In particular, the only option is line 484, where you set the flatfield value to 1.0 if the pixel value falls below some user-defined sigma cutoff (e.g. if I set filtering=5 then all values below 5 standard deviations of 1.0 gets replaced with 1.0). 

I don't think this does enough though. Firstly, there is no upper filtering for removing the NIRC2 pixels that always show a high value. Secondly, it is important to note the locations of these bad pixels so that we smooth out the science frames too.

I would like to ask for two additional features for the "master" and "masterFlat" function:
1. Add a user defined keyword for an upper filtering.
2. The function should return the locations of filtered pixels. Maybe as an array of 0 and 1 where 0's are locations not filtered and 1's are locations filtered (or boolean array).

In our "Friends of Hot Jupiters" work, I found that it's best for us to ignore all flatfield pixels less than 0.1 (absolute value) and flatfield pixels 10 standard deviations greater than the median. I came to these values by examining the NIRC2 engineering manual and from empirical trials to determine what worked. I don't remember the URL where I downloaded the manual but I can send it via email if you have not yet seen it.

**Comment by oabsil** [comment]
Hi Henry,

Olivier Wertz is currently finishing a four-month, intensive training to 
learn German before taking on his next postdoc in Bonn. He might not be 
able to answer and/or implement the proposed changes within the next few 
weeks.

If you feel comfortable enough with python and with the 
NIRC2_Preprocessing package to implement these changes yourself, please 
go ahead. Note that there are some bad-pixel removal tools in VIP that 
could be useful (although your requests look pretty basic and probably 
don't need very specific tools to be implemented).

Cheers,
Olivier.

Le 22/06/16 à 06:32, Henry Ngo a écrit :

> Hello!
> 
> Recently, when Dimitri and I tried to build a super-cube with vip for 
> RDI processing, we notice that we have a lot of trouble finding frames 
> with enough correlation. After inspecting the frames, we see that 
> there are image artifacts due to bad pixels that might be making it 
> hard for VIP to find correlations.
> 
> I inspected the "master" method in NIRC2_Preprocessing (the wrapper is 
> "masterFlat") and notice that there is currently very little filtering 
> options for creating the master flat.
> 
> In particular, the only option is line 484, where you set the 
> flatfield value to 1.0 if the pixel value falls below some 
> user-defined sigma cutoff (e.g. if I set filtering=5 then all values 
> below 5 standard deviations of 1.0 gets replaced with 1.0).
> 
> I don't think this does enough though. Firstly, there is no upper 
> filtering for removing the NIRC2 pixels that always show a high value. 
> Secondly, it is important to note the locations of these bad pixels so 
> that we smooth out the science frames too.
> 
> I would like to ask for two additional features for the "master" method:
> 1. Add a user defined keyword for an upper filtering.
> 1. The routine should return the locations of filtered pixels. Maybe
>    as an array of 0 and 1 where 0's are locations not filtered and
>    1's are locations filtered (or boolean array).
> 
> In our "Friends of Hot Jupiters" work, I found that it's best for us 
> to ignore all flatfield pixels less than 0.1 (absolute value) and 
> flatfield pixels 10 standard deviations greater than the median. I 
> came to these values by examining the NIRC2 engineering manual and 
> from empirical trials to determine what worked. I don't remember the 
> URL where I downloaded the manual but I can send it via email if you 
> have not yet seen it.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> https://github.com/vortex-exoplanet/NIRC2_Preprocessing/issues/8, or 
> mute the thread 
> https://github.com/notifications/unsubscribe/AMHAnLfAocupYZOJQ_0EH1mYvsogGlpTks5qOLrPgaJpZM4I7ZaY.

## 

---

Dr. Olivier ABSIL
F.R.S.-FNRS Research Associate
Space sciences, Technologies & Astrophysics Research unit (STAR)
Université de Liège (ULg)                Tel: +32-(0)4-366.97.24
19c allée du Six Août                    Fax: +32-(0)4-366.97.46
B-4000 Sart-Tilman             Email: absil (at) astro.ulg.ac.be
Homepage: https://sites.google.com/site/olivierabsil/

## VORTEX project: http://www.vortex.ulg.ac.be

**Comment by henry-ngo** [comment]
Okay, I'll make the changes on my local copy of NIRC2_Preprocessing then :)

**Comment by oabsil** [comment]
Good idea ... and if you're satisfied with your changes, please consider 
pushing them to github. ;-)

Le 22/06/16 à 17:04, Henry Ngo a écrit :

> Okay, I'll make the changes on my local copy of NIRC2_Preprocessing 
> then :)
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> https://github.com/vortex-exoplanet/NIRC2_Preprocessing/issues/8#issuecomment-227773236, 
> or mute the thread 
> https://github.com/notifications/unsubscribe/AMHAnPgaWGIo3ucrrwLUD_IZa8CIO-JLks5qOU73gaJpZM4I7ZaY.

## 

---

Dr. Olivier ABSIL
F.R.S.-FNRS Research Associate
Space sciences, Technologies & Astrophysics Research unit (STAR)
Université de Liège (ULg)                Tel: +32-(0)4-366.97.24
19c allée du Six Août                    Fax: +32-(0)4-366.97.46
B-4000 Sart-Tilman             Email: absil (at) astro.ulg.ac.be
Homepage: https://sites.google.com/site/olivierabsil/

## VORTEX project: http://www.vortex.ulg.ac.be

**Comment by henry-ngo** [comment]
Okay, Carlos taught us how to fork repositories and create pull requests with our changes. So I just submitted one with updates!
